version: '3'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
  php:
    build: ./docker/php
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
      - sqlsrv
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: WRaZqHk4M8EB
      MYSQL_USER: search_user
      MYSQL_PASSWORD: Q1oBpQ3fDbJE
      MYSQL_DATABASE: search
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
  sqlsrv:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: sample_PASSword33
    ports:
      - "1433:1433"


