version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_role_arn: arn:aws:iam::123456789012:role/ecsTaskRole
  task_execution_role: ecsTaskExecutionRole
  task_size:
    cpu_limit: 2048
    mem_limit: 4096
  services:
    web:
      mem_limit: 128M
      mem_reservation: 128M
    php:
      cpu_shares: 2048
      mem_limit: 3GB
      mem_reservation: 3GB
      essential: true

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-xxxx
        - subnet-yyyy
      security_groups:
        - sg-zzzz
      assign_public_ip: ENABLED
