version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_role_arn: arn:aws:iam::123456789012:role/ecsTaskRole
  task_execution_role: ecsTaskExecutionRole
  task_size:
    cpu_limit: 256
    mem_limit: 1GB
  services:
    web:
    php:
      essential: true

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-xxxx
        - subnet-yyyy
      security_groups:
        - sg-zzzz
      assign_public_ip: ENABLED
